
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { loadEnvConfig } from "@next/env";
import { defineConfig } from "prisma/config";

const { combinedEnv } = loadEnvConfig(process.cwd());

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // From the schema file's perspective (prisma/), "file:./dev.db" resolves to prisma/dev.db
    // which matches what the app expects via DATABASE_URL="file:./prisma/dev.db" at project root
    url: "file:./dev.db",
  },
});
